Pri.Ca.Web/Models/ErrorViewModel.cs
namespace Pri.Ca.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pri.Ca.Web/ViewModels/BaseViewModel.cs
namespace Pri.Ca.Web.ViewModels
{
    public class BaseViewModel
    {
        public int Id { get; set; }
        public string Value { get; set; }
    }
}

Pri.Ca.Web/ViewModels/GamesIndexViewModel.cs
namespace Pri.Ca.Web.ViewModels
{
    public class GamesIndexViewModel
    {
        public IEnumerable<BaseViewModel> Games { get; set; }
    }
}

Pri.Ca.Web/ViewModels/GamesInfoViewModel.cs
namespace Pri.Ca.Web.ViewModels
{
    public class GamesInfoViewModel : BaseViewModel
    {
        public string Description { get; set; }
        public BaseViewModel Publisher { get; set; }
        public IEnumerable<BaseViewModel> Genres { get; set; }
    }
}

Pri.Ca.Web/Controllers/GamesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pri.Ca.Core.Interfaces;
using Pri.Ca.Core.Interfaces.Repositories;
using Pri.Ca.Infrastructure.Data;
using Pri.Ca.Web.ViewModels;

namespace Pri.Ca.Web.Controllers
{
    public class GamesController : Controller
    {
        private readonly IGameService _gameService;

        public GamesController(IGameService gameService)
        {
            _gameService = gameService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _gameService.GetAllAsync();
            
            var gamesIndexViewModel = new GamesIndexViewModel
            {
                Games = result.Games.Select(g => new BaseViewModel 
                    {
                        Id = g.Id,
                        Value = g.Title
                    })
            };            
            return View(gamesIndexViewModel);
        }
        public async Task<IActionResult> Info(int id)
        {
            var result = await _gameService.GetByIdAsync(id);
            if(result == null)
            {
                return NotFound(result.Errors);
            }
            var gamesInfoViewModel = new GamesInfoViewModel 
            {
                Id = result.Games.First().Id,
                Value = result.Games.First().Title,
                Description = result.Games.First().Description,
                Publisher = new BaseViewModel 
                {
                    Id = result.Games.First().Publisher.Id,
                    Value = result.Games.First().Publisher.Name,
                },
                Genres = result.Games.First().Genres.Select(g => new BaseViewModel
                {
                    Id = g.Id,
                    Value = g.Name
                })
            };
            return View(gamesInfoViewModel);
        }
    }
}

Pri.Ca.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pri.Ca.Web.Models;
using System.Diagnostics;

namespace Pri.Ca.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pri.Ca.Web/Views/Games/Index.cshtml
@model Pri.Ca.Web.ViewModels.GamesIndexViewModel
<div class="row">
    <div class="col col-lg-6 mx-auto">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Info</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var game in Model.Games)
                { 
                    <tr>
                        <td>
                            @game.Value
                        </td>
                        <td>
                            <a asp-controller="Games"
                               asp-action="Info"
                               asp-route-id="@game.Id"
                               class="btn btn-outline-info">Info</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Pri.Ca.Web/Views/Games/Info.cshtml
@model GamesInfoViewModel
@{
    ViewData["Title"] = "Info";
}
<div class="row">
    <div class="col col-lg-3 mx-auto">
        <div class="card" style="width: 18rem;">
            <!--tips: add .text-center,.text-right to the .card to change card text alignment-->
            <img src="https://placehold.co/600x400/000000/FFFFFF/png" class="card-img-top" alt="@Model.Value">
            <div class="card-body">
                <h5 class="card-title">@Model.Value</h5>
                <h6 class="card-subtitle mb-2 text-muted">@Model.Publisher.Value</h6>
                <p class="card-text">@Model.Description</p>
                @foreach(var genre in Model.Genres)
                { 
                    <h6 class="card-subtitle mb-2 text-muted">@genre.Value</h6>
                }
                <a asp-controller="Games"
                   asp-action="Index"
                   class="btn btn-primary">Back</a>
            </div>
        </div>
    </div>
</div>

Pri.Ca.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pri.Ca.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pri.Ca.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pri.Ca.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pri.Ca.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pri.Ca.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>